/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as balancerFlashLoanArbSol from "./BalancerFlashLoanArb.sol";
export type { balancerFlashLoanArbSol };
