[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@balancer-labs/=node_modules/@balancer-labs/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200

# Fuzzテスト設定
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x42'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# テスト設定
[profile.test]
verbosity = 3 