[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
    "@balancer-labs/=node_modules/@balancer-labs/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

# Fuzzテスト設定
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x42'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# 最適化設定
[profile.default.optimizer]
enabled = true
runs = 200

# テスト設定
[profile.test]
verbosity = 3 